logging:
  level: INFO
  loggers:
    "org.magneato": DEBUG

#Server configuration.
server:
  type: jettyauthserver
  applicationConnectors:
    - type: http
      port: 9090

#Uploader Configuration
gpxUploader:
  template:  "{\"title\":\"%1$s\",\"child\":false,\"activity_c\":\"\",\"trip_date\":\"%11$s\",\"difficulty_c\":{\"rating\":\"\"},\"ski_difficulty_c\":{\"rating\":\"\"},\"technical_c\":{\"imperial\":\"false\",\"orientation\":\"\",\"distance\":%2$.3f,\"climb\":%3$d,\"descent\":%4$d,\"min\":%5$d,\"max\":%6$d,\"location\":{\"lat\":%7$s,\"lon\":%8$s}},%9$s,\"metadata\":%10$s}";
  editTemplate: tripreport
  viewTemplate: tripreport

# Default Administrator User, update the password before putting into production
login: admin
password: secure

# External Resources
assets:
  mappings:
    /assets: /library
  # http://localhost:8080/library/images/logo.png
  overrides:
     /library/images: "/home/david/src/dropwizard/Magneato3/assets"
#     /library/images: "/Users/TBSL1730/src/Magneato-3/assets"
#    /library/templates: "/home/david/src/dropwizard/Magneato3/templates"

#
# Available edit and display templates
#
templates:
  - name: simple
    description: Simple page template containing title, edit box and attachments
    views:
      - simple
  - name: tripreport
    description: Create trip reports, can attach jpegs and gpx files
    views:
      - skitour
      - mtb

elasticSearch:
  slop: 2
  minShouldMatch: 75%
  clusterName: elastic-cluster
  indexName: my-index
  hostname: localhost
  port: 9300
