logging:
  level: INFO
  loggers:
    "org.magneato": DEBUG

#Server configuration.
server:
  type: jettyauthserver
  applicationConnectors:
    - type: http
      port: 9090

# Default Administrator User, update the password before putting into production
login: admin
password: secure

# External Resources
assets:
  mappings:
    /assets: /library
  # http://localhost:8080/library/images/logo.png
  overrides:
    /library/images/: "/Users/TBSL1730/src/Magneato-3/assets"
    /library/templates/: "/Users/TBSL1730/src/Magneato-3/assets"

#
# Available edit and display templates
#
templates:
  - name: simple
    description: simple page template containing title, edit box and attachments
    views:
      - simple
  - name: trip_report
    description: A template for creating trip reports, can attach jpegs and gpx files
    views:
      - ski_tour
      - mtb


